name: Telegram Notifier

# triggers for notifying
#  these are some important trigger cases could be change as need
# check here https://developer.github.com/webhooks/
on:
  issue_comment:
    types: created
  issues:
    types: [opened, edited, pinned, closed, reopened, assigned, labeled]
  pull_request:
    types: [opened, closed, edited, ready_for_review, review_requested, reopened]
  pull_request_review_comment:
    types: created
  push:

jobs:
  build:
    name: Notifier
    runs-on: ubuntu-latest

    steps:
      - name: push
        uses: daniellimws/TelegramBridge@master
        if: github.event_name == 'push'
        with:
          chat: ${{ secrets.chat }}
          token: ${{ secrets.token }}
          message: |
            ${{ github.actor }} pushed to ${{ github.ref }} ${{ github.event.compare }}
            ${{ join(github.event.commits.*.message) }}
      - name: pull request
        uses: daniellimws/TelegramBridge@master
        if: github.event_name == 'pull_request'
        with:
          chat: ${{ secrets.chat }}
          token: ${{ secrets.token }}
          message: |
            ${{ github.actor }} ${{ github.event.action }} PR #${{ github.event.pull_request.number }}: "${{ github.event.pull_request.title }}" (${{ github.event.pull_request.html_url }})
      - name: issue
        uses: daniellimws/TelegramBridge@master
        if: github.event_name == 'issues'
        with:
          chat: ${{ secrets.chat }}
          token: ${{ secrets.token }}
          message: |
            ${{ github.actor }} ${{ github.event.action }} issue #${{ github.event.issue.number }}: "${{ github.event.issue.title }}" (${{ github.event.issue.html_url }})
